dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - find docsite -iname '*.py' | xargs pylint --load-plugins pylint_django --ignored-classes=User
  - python manage.py migrate
  - python manage.py test
